<?php
/**
 * @var $block Magento\Catalog\Block\Product\View
 * @var $_helper Spirit\Skroutz\ViewModel\Config
 */
$_product = $block->getProduct();
$_helper  = $block->getData('config');
if (! empty($_helper->getReviewTheme())): ?>
    <div id="skroutz-product-reviews-<?= $block->escapeHtml($_helper->getReviewTheme()); ?>"
         data-product-id="<?= $block->escapeHtml($_product->getSku()); ?>">
    </div>
<?php endif; ?>
