<?php
/**
 * Copyright © Spirit Digital Agency. All rights reserved.
 * See LICENSE.md for license details.
 */

/**
 * @var \Magento\Catalog\Block\Product\View $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Spirit\Skroutz\ViewModel\Config $config
 */
$config = $block->getData('config');
$theme = $config->getReviewTheme();
$product = $block->getProduct();
if ($theme === '' || !$product) {
    return;
}
?>
<div id="skroutz-product-reviews-<?= $escaper->escapeHtmlAttr($theme) ?>"
     data-product-id="<?= $escaper->escapeHtmlAttr((string)$product->getData($config->getUniqueId())) ?>">
</div>
