<?php
/**
 * Copyright © Spirit Digital Agency. All rights reserved.
 * See LICENSE.md for license details.
 */

/**
 * @var \Spirit\Skroutz\Block\Success $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
if (!$block->getOrder()) {
    return;
}

$script = 'skroutz_analytics("ecommerce", "addOrder", ' . $block->getOrderJson() . ');';
foreach ($block->getItemsJson() as $itemJson) {
    $script .= PHP_EOL . 'skroutz_analytics("ecommerce", "addItem", ' . $itemJson . ');';
}
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $script, false) ?>
