<?php
/**
 * @var \Spirit\Skroutz\Block\Success $block
 */
?>
<?php if ($block->getOrderId()): ?>
    <!-- SKROUTZ ANALYTICS CODE start -->
    <script type="text/javascript">
      skroutz_analytics("ecommerce", "addOrder", JSON.stringify({
        order_id: '<?= /* @noEscape */ $block->getOrderId(); ?>',
        revenue: '<?= /* @noEscape */ $block->getTotal(); ?>',
        shipping: '<?= /* @noEscape */ $block->getShippingCost(); ?>',
        tax: '<?= /* @noEscape */ $block->getTaxAmount(); ?>',
        paid_by: '<?= /* @noEscape */ $block->getPaymentMethodTitle(); ?>',
        paid_by_descr: '<?= /* @noEscape */ $block->getPaymentMethodCode(); ?>'
      }));
      <?php foreach ($block->getItems() as $item): ?>
      skroutz_analytics("ecommerce", "addItem", JSON.stringify({
        order_id: "<?= /* @noEscape */ $block->getOrderId(); ?>",
        product_id: "<?= /* @noEscape */ $block->getProductId($item); ?>",
        name: "<?= $block->escapeJs($item->getName()); ?>",
        price: "<?= /* @noEscape */ $item->getPriceInclTax(); ?>",
        quantity: "<?= /* @noEscape */ $item->getQtyOrdered(); ?>"
      }));
      <?php endforeach; ?>
    </script>
    <!-- SKROUTZ ANALYTICS CODE end -->
<?php endif; ?>
